=== Shi-Yueyang/binmaster/format_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Binary Format Definition",
  "type": "object",
  "required": ["fields"],
  "properties": {
    "endianness": {
      "type": "string",
      "enum": ["little", "big"],
      "default": "little",
      "description": "Byte order for multi-byte values"
    },
    "description": {
      "type": "string",
      "description": "Human-readable description of the format"
    },
    "version": {
      "type": "string",
      "description": "Version of the format specification"
    },
    "fields": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/field"
      },
      "description": "List of fields in the binary format"
    }
  },
  "definitions": {
    "field": {
      "type": "object",
      "required": ["name", "type"],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the field"
        },
        "type": {
          "type": "string",
          "enum": [
            "int8", "uint8", "int16", "uint16", "int32", "uint32", "int64", "uint64",
            "float32", "float64", "char", "string", "array", "struct"
          ],
          "description": "Data type of the field"
        },
        "size": {
          "type": "integer",
          "minimum": 1,
          "description": "Size in bytes (for fixed-size strings) or element count (for fixed-size arrays)"
        },
        "encoding": {
          "type": "string",
          "default": "utf-8",
          "description": "Text encoding for string fields"
        },
        "length_field": {
          "type": "string",
          "description": "Name of field that contains the length for variable-size arrays"
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/field"
          },
          "description": "Nested fields for struct types"
        },
        "element_type": {
          "type": "string",
          "description": "Type of array elements"
        },
        "element_fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/field"
          },
          "description": "Field definitions for struct array elements"
        },
        "description": {
          "type": "string",
          "description": "Human-readable description of the field"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "array"
              }
            }
          },
          "then": {
            "required": ["element_type"]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "struct"
              }
            }
          },
          "then": {
            "required": ["fields"]
          }
        }
      ]
    }
  }
}

=== Shi-Yueyang/binmaster/examples/cn_map_example/cn_map_fix_format.json
{
  "endianness": "little",
  "description": "CN map fix",
  "version": "1.0",
  "fields": [
    { "name": "file_type", "type": "uint8" },
    { "name": "structure_version", "type": "uint16" },
    { "name": "data_version", "type": "uint16" },
    { "name": "station_id", "type": "uint16" },
    {
      "name": "bos_cnt",
      "type": "uint8",
      "function": "count",
      "function_parameters": {
        "key": "boses"
      }
    },
    {
      "name": "boses",
      "type": "array",
      "length_field": "bos_cnt",
      "element_type": "struct",
      "element_fields": [
        { "name": "bos_near_track_id", "type": "uint8" },
        { "name": "bos_near_addr_offset", "type": "uint16" }
      ]
    },
    {
      "name": "eos_cnt",
      "type": "uint8",
      "function": "count",
      "function_parameters": {
        "key": "eoses"
      }
    },
    {
      "name": "eoses",
      "type": "array",
      "length_field": "eos_cnt",
      "element_type": "struct",
      "element_fields": [
        { "name": "eos_near_track_id", "type": "uint8" },
        { "name": "eos_near_addr_offset", "type": "uint16" }
      ]
    },
    { "name": "switch_addr_offset", "type": "uint16" },
    { "name": "balise_addr_offset", "type": "uint16" },
    { "name": "signal_addr_offset", "type": "uint16" },
    { "name": "track_addr_offset", "type": "uint16" },
    {
      "name": "fix_points",
      "type": "array",
      "size": -1,
      "element_type": "union",
      "discriminator_field": "point_type",
      "union_variants":{
        "0":[
          {"name":"point_type","type":"uint8"},
          {"name":"neighbor_addr_offset","type":"uint16"},
          {"name":"tsrs_id","type":"uint32"},
          {"name":"near_station_id","type":"uint16"},
          {"name":"near_station_boundary_type","type":"uint8"},
          {"name":"near_station_track_id","type":"uint8"},
          {"name":"location","type":"int32"},
          {"name":"track_id","type":"uint8"}
        ],
        "1":[
          {"name":"point_type","type":"uint8"},
          {"name":"neighbor_addr_offset","type":"uint16"},
          {"name":"tsrs_id","type":"uint32"},
          {"name":"near_station_id","type":"uint16"},
          {"name":"near_station_boundary_type","type":"uint8"},
          {"name":"near_station_track_id","type":"uint8"},
          {"name":"location","type":"int32"},
          {"name":"track_id","type":"uint8"}
        ],
        "254":[
          {"name":"point_type","type":"uint8"},
          {"name":"neighbor_addr_offset","type":"uint16"},
          {"name":"tsrs_id","type":"uint32"},
          {"name":"near_station_id","type":"uint16"},
          {"name":"near_station_boundary_type","type":"uint8"},
          {"name":"near_station_track_id","type":"uint8"},
          {"name":"location","type":"int32"},
          {"name":"track_id","type":"uint8"}
        ],
        "255":[
          {"name":"point_type","type":"uint8"},
          {"name":"neighbor_addr_offset","type":"uint16"},
          {"name":"tsrs_id","type":"uint32"},
          {"name":"near_station_id","type":"uint16"},
          {"name":"near_station_boundary_type","type":"uint8"},
          {"name":"near_station_track_id","type":"uint8"},
          {"name":"location","type":"int32"},
          {"name":"track_id","type":"uint8"}
        ]
      }
    }
  ]
}

=== Shi-Yueyang/binmaster/examples/cn_map_example/cn_map_format.json
{
  "endianness": "little",
  "description": "CN map index",
  "version": "1.0",
  "fields": [
    { "name": "file_type", "type": "uint8" },
    { "name": "structure_version", "type": "uint16" },
    { "name": "data_version", "type": "uint16" },
    { "name": "file_size", "type": "uint16" },
    { "name": "tsrs_id", "type": "uint32" },
    { "name": "station_cnt", "type": "uint8" },
    {
      "name": "stations",
      "type": "array",
      "length_field": "station_cnt",
      "element_type": "struct",
      "element_fields": [
        { "name": "station_id", "type": "uint16" },
        {
          "name": "station_abbr",
          "type": "string",
          "size": 8,
          "encoding": "ascii"
        },
        {
          "name": "station_name",
          "type": "string",
          "size": 16,
          "encoding": "gb18030"
        },
        { "name": "lowbound_station_cnt", "type": "uint8" },
        { 
          "name": "lowbound_station_id", 
          "type": "uint16",
          "condition": "lowbound_station_cnt > 0"
        },
        { "name": "highound_station_cnt", "type": "uint8" },
        { 
          "name": "highound_station_id", 
          "type": "uint16",
          "condition": "highound_station_cnt > 0"
        },
        { "name": "geo_file_size", "type": "uint16" },
        { "name": "geo_file_crc", "type": "uint32" },
        { "name": "geo_file_version", "type": "uint16" },
        { "name": "min_latitude", "type": "uint32" },
        { "name": "min_longitude", "type": "uint32" },
        { "name": "max_latitude", "type": "uint32" },
        { "name": "max_longitude", "type": "uint32" },
        { "name": "fix_file_size", "type": "uint16" },
        { "name": "fix_file_crc", "type": "uint32" },
        { "name": "fix_file_version", "type": "uint16" }
      ]
    },

    { 
      "name": "crc", 
      "type": "uint32",
      "function": "crc32",
      "function_scope": "all_previous",
      "function_parameters": {
        "initial_value": 0
      }
    }
  ]
}

=== Shi-Yueyang/binmaster/examples/01_simple_message/message_format.json
{
  "endianness": "little",
  "description": "Simple message format with header and payload",
  "version": "1.0",
  "fields": [
    {
      "name": "header",
      "type": "struct",
      "description": "Message header",
      "fields": [
        {
          "name": "magic",
          "type": "uint32",
          "description": "Magic number to identify format"
        },
        {
          "name": "version",
          "type": "uint16",
          "description": "Format version"
        },
        {
          "name": "message_type",
          "type": "uint16",
          "description": "Type of message"
        },
        {
          "name": "payload_size",
          "type": "uint32",
          "description": "Size of payload in bytes"
        }
      ]
    },
    {
      "name": "sender",
      "type": "string",
      "size": 64,
      "encoding": "utf-8",
      "description": "Sender identifier (fixed 64 bytes)"
    },
    {
      "name": "timestamp",
      "type": "uint64",
      "description": "Unix timestamp"
    },
    {
      "name": "data",
      "type": "array",
      "length_field": "header.payload_size",
      "element_type": "uint8",
      "description": "Variable-length payload data"
    }
  ]
}

=== Shi-Yueyang/binmaster/examples/02_3d_model/model_format.json
{
  "endianness": "little",
  "description": "3D model file format with vertices, textures, and materials",
  "version": "2.1",
  "fields": [
    {
      "name": "file_header",
      "type": "struct",
      "description": "File header information",
      "fields": [
        {
          "name": "signature",
          "type": "string",
          "size": 8,
          "description": "File format signature"
        },
        {
          "name": "version_major",
          "type": "uint16",
          "description": "Major version number"
        },
        {
          "name": "version_minor",
          "type": "uint16",
          "description": "Minor version number"
        },
        {
          "name": "vertex_count",
          "type": "uint32",
          "description": "Number of vertices"
        },
        {
          "name": "face_count",
          "type": "uint32",
          "description": "Number of faces"
        },
        {
          "name": "material_count",
          "type": "uint32",
          "description": "Number of materials"
        }
      ]
    },
    {
      "name": "vertices",
      "type": "array",
      "length_field": "file_header.vertex_count",
      "element_type": "struct",
      "element_fields": [
        {
          "name": "position",
          "type": "struct",
          "fields": [
            {"name": "x", "type": "float32"},
            {"name": "y", "type": "float32"},
            {"name": "z", "type": "float32"}
          ]
        },
        {
          "name": "normal",
          "type": "struct",
          "fields": [
            {"name": "x", "type": "float32"},
            {"name": "y", "type": "float32"},
            {"name": "z", "type": "float32"}
          ]
        },
        {
          "name": "uv",
          "type": "struct",
          "fields": [
            {"name": "u", "type": "float32"},
            {"name": "v", "type": "float32"}
          ]
        },
        {
          "name": "color",
          "type": "struct",
          "fields": [
            {"name": "r", "type": "uint8"},
            {"name": "g", "type": "uint8"},
            {"name": "b", "type": "uint8"},
            {"name": "a", "type": "uint8"}
          ]
        }
      ],
      "description": "Array of vertex data"
    },
    {
      "name": "faces",
      "type": "array",
      "length_field": "file_header.face_count",
      "element_type": "struct",
      "element_fields": [
        {"name": "v1", "type": "uint32", "description": "First vertex index"},
        {"name": "v2", "type": "uint32", "description": "Second vertex index"},
        {"name": "v3", "type": "uint32", "description": "Third vertex index"},
        {"name": "material_id", "type": "uint16", "description": "Material index"}
      ],
      "description": "Array of face definitions"
    },
    {
      "name": "materials",
      "type": "array",
      "length_field": "file_header.material_count",
      "element_type": "struct",
      "element_fields": [
        {
          "name": "name",
          "type": "string",
          "size": 32,
          "description": "Material name"
        },
        {
          "name": "diffuse_color",
          "type": "struct",
          "fields": [
            {"name": "r", "type": "float32"},
            {"name": "g", "type": "float32"},
            {"name": "b", "type": "float32"},
            {"name": "a", "type": "float32"}
          ]
        },
        {
          "name": "specular_color",
          "type": "struct",
          "fields": [
            {"name": "r", "type": "float32"},
            {"name": "g", "type": "float32"},
            {"name": "b", "type": "float32"}
          ]
        },
        {
          "name": "shininess",
          "type": "float32",
          "description": "Specular shininess factor"
        },
        {
          "name": "texture_path",
          "type": "string",
          "description": "Path to texture file (variable length)"
        }
      ],
      "description": "Array of material definitions"
    }
  ]
}

=== Shi-Yueyang/binmaster/examples/03_custom_format/custom_packet_format.json
{
  "endianness": "big",
  "description": "Network packet format",
  "version": "1.0",
  "fields": [
    {
      "name": "packet_header",
      "type": "struct",
      "fields": [
        {
          "name": "packet_id",
          "type": "uint32"
        },
        {
          "name": "sequence_number",
          "type": "uint32"
        },
        {
          "name": "flags",
          "type": "uint16"
        },
        {
          "name": "data_length",
          "type": "uint16"
        }
      ]
    },
    {
      "name": "source_address",
      "type": "array",
      "size": 4,
      "element_type": "uint8"
    },
    {
      "name": "destination_address",
      "type": "array",
      "size": 4,
      "element_type": "uint8"
    },
    {
      "name": "payload",
      "type": "array",
      "length_field": "packet_header.data_length",
      "element_type": "uint8"
    },
    {
      "name": "checksum",
      "type": "uint32"
    }
  ]
}
